dbt_with_cloud_run:
  outputs:
    dev:
      dataset: processed_data
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: amadou
      threads: 1
      type: bigquery
  target: dev